# Common settings
sudo: required
dist: precise

# Enable C++ support
language: cpp

matrix:
  include:
   - os: linux
     compiler: gcc
     addons:
       apt:
         sources:
          - george-edison55-precise-backports
          - ubuntu-toolchain-r-test
         packages:
          - cmake
          - cmake-data
          - gcc-6
          - g++-6
     env: TARGET=gcc C_COMPILER=gcc-6 CXX_COMPILER=g++-6
   - os: linux
     compiler: clang
     addons:
       apt:
         sources:
          - george-edison55-precise-backports
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.9
         packages:
          - cmake
          - cmake-data
          - clang-3.9
     env: TARGET=clang C_COMPILER=clang-3.9 CXX_COMPILER=clang++-3.9
#   - os: linux
#     compiler: gcc
#     addons:
#       apt:
#         sources:
#          - george-edison55-precise-backports
#          - ubuntu-toolchain-r-test
#         packages:
#          - cmake
#          - cmake-data
#     env: TARGET=gcc-arm-none-eabi
#   - os: linux
#     compiler: clang
#     addons:
#       apt:
#         sources:
#          - george-edison55-precise-backports
#          - ubuntu-toolchain-r-test
#          - llvm-toolchain-precise-3.9
#         packages:
#          - cmake
#          - cmake-data
#          - clang-3.9
#     env: TARGET=clang-arm-none-eabi C_COMPILER=clang-3.9 CXX_COMPILER=clang++-3.9

#before_script:
# - ./.travis/setup.sh
# - export PATH=$PATH:/tmp/gcc-arm-none-eabi/bin

script:
 - ./.travis/build.sh
