dist: precise
sudo: false
language: c++
os: linux

cache:
  directories:
   - $HOME/toolchains

env: TOOLCHAIN=gcc C_COMPILER=gcc-6 CXX_COMPILER=g++-6

addons:
  apt:
    sources:
     - george-edison55-precise-backports
     - ubuntu-toolchain-r-test
    packages:
     - cmake cmake-data
     - gcc-6 g++-6

matrix:
  include:
    - env: TOOLCHAIN=gcc C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9
      addons:
        apt:
          sources:
           - george-edison55-precise-backports
           - ubuntu-toolchain-r-test
          packages:
           - cmake cmake-data
           - gcc-4.9 g++-4.9

    - env: TOOLCHAIN=clang C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
      addons:
        apt:
          sources:
           - george-edison55-precise-backports
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.8
          packages:
           - cmake cmake-data
           - clang-3.8

    - env: TOOLCHAIN=clang C_COMPILER=clang-3.9 CXX_COMPILER=clang++-3.9
      addons:
        apt:
          sources:
           - george-edison55-precise-backports
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.9
          packages:
           - cmake cmake-data
           - clang-3.9

    - env: TOOLCHAIN=gcc-arm-none-eabi VERSION=4.9
      addons:
        apt:
          sources:
           - george-edison55-precise-backports
          packages:
           - lib32z1 lib32bz2-1.0 lib32ncurses5
           - cmake cmake-data

    - env: TOOLCHAIN=gcc-arm-none-eabi VERSION=5.4
      addons:
        apt:
          sources:
           - george-edison55-precise-backports
          packages:
           - lib32z1 lib32bz2-1.0 lib32ncurses5
           - cmake cmake-data

    - env: TOOLCHAIN=clang-arm-none-eabi VERSION=5.4 C_COMPILER=clang-3.9 CXX_COMPILER=clang++-3.9
      addons:
        apt:
          sources:
           - george-edison55-precise-backports
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.9
          packages:
           - lib32z1 lib32bz2-1.0 lib32ncurses5
           - cmake cmake-data
           - clang-3.9

before_script:
 - ./.travis/setup.sh
 - export PATH=/tmp/gcc-arm-none-eabi/bin:$PATH

script:
 - ./.travis/build.sh
